src/StatsBro.Host.Panel/Models/Forms/Settings/GeneralSettingsFormModel.cs
/* Copyright StatsBro.io and/or licensed to StatsBro.io under one
 * or more contributor license agreements.
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the Server Side Public License, version 1

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * Server Side Public License for more details.

 * You should have received a copy of the Server Side Public License
 * along with this program. If not, see
 * <https://github.com/StatsBro/statsbro/blob/main/LICENSE>.
 */
using System.ComponentModel.DataAnnotations;

namespace StatsBro.Host.Panel.Models.Forms.Settings
{
    public class GeneralSettingsFormModel : FormModel
    {
        public Guid Id { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Podaj adres twojej strony")]
        [DataType(DataType.Url, ErrorMessage = "Adres twojej strony ma nieprawidłowy format")]
        public string SiteUrl { get; set; } = null!;

        public string? Domain { get; set; }

        public string? PersistQueryParamsList { get; set; }
        public string? IgnoreIPsList { get; set; }
    }
}

src/StatsBro.Host.Panel/Models/Forms/Settings/SharingSettingsFormModel.cs
/* Copyright StatsBro.io and/or licensed to StatsBro.io under one
 * or more contributor license agreements.
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the Server Side Public License, version 1

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * Server Side Public License for more details.

 * You should have received a copy of the Server Side Public License
 * along with this program. If not, see
 * <https://github.com/StatsBro/statsbro/blob/main/LICENSE>.
 */

namespace StatsBro.Host.Panel.Models.Forms.Settings
{
    public class SharingSettingsFormModel : FormModel
    {
        public Guid Id { get; set; }
        
        public bool LinkSharingEnabled { get; set; }

        public string? LinkSharingUrl { get; set; }

        public bool ApiKeyEnabled { get; set; }

        public string? ApiKeyValue { get; set; }
    }
}

src/StatsBro.Host.Panel/Controllers/StatsController.cs
/* Copyright StatsBro.io and/or licensed to StatsBro.io under one
 * or more contributor license agreements.
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the Server Side Public License, version 1

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * Server Side Public License for more details.

 * You should have received a copy of the Server Side Public License
 * along with this program. If not, see
 * <https://github.com/StatsBro/statsbro/blob/main/LICENSE>.
 */
﻿namespace StatsBro.Host.Panel.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StatsBro.Domain.Models;
using StatsBro.Domain.Models.Request;
using StatsBro.Host.Panel.Extensions;
using StatsBro.Host.Panel.Logic;
using StatsBro.Host.Panel.Models;
using System.Data;
using System.Web;
using static StatsBro.Host.Panel.Extensions.StatsRequestLinkBuilder;

[Authorize]
public class StatsController : Controller
{
    private readonly ILogger<StatsController> _logger;
    private readonly StatsLogic _statsLogic;
    private readonly SiteLogic _siteLogic;
    private readonly OrganizationLogic _organizationLogic;
    private readonly ISubscriptionPlanGuard _subscriptionPlanGuard;

    public StatsController(
        StatsLogic statsLogic,
        SiteLogic siteLogic,
        OrganizationLogic organizationLogic,
        ISubscriptionPlanGuard subscriptionPlanGuard,
        ILogger<StatsController> logger)
    {
        _logger = logger;
        _statsLogic = statsLogic;
        _siteLogic = siteLogic;
        _organizationLogic = organizationLogic;
        _subscriptionPlanGuard = subscriptionPlanGuard;
    }

    [HttpGet("Stats/View/{siteId}")]
    public async Task<IActionResult> ViewAsync([FromRoute]Guid siteId, [FromQuery]StatsRequest request, CancellationToken cancellationToken)
    {
        var userId = HttpContext.User.GetUserId();
        var organizationId = HttpContext.User.GetOrganizationId();
        var organization = await _organizationLogic.GetOrganizationAsync(organizationId);
        if (!_subscriptionPlanGuard.IsSubscriptionPlanExpired(organization))
        {
            return RedirectToAction("Index", "Payment");
        }

        var site = await this._siteLogic.GetSiteAsync(userId, organizationId, siteId);
        if (site == null)
        {
            return NotFound();
        }

        request.To = request.To.Value.AddDays(1).AddSeconds(-1);

        ViewBag.Request = request;
        ViewBag.LinkBuilder = new StatsRequestLinkBuilder(request);
        var stats = await _statsLogic.GetStatsAsync(site, request, cancellationToken);
        var viewModel = this.StatsToViewModel(stats, site);

        return View(viewModel);
    }

    [HttpGet("Stats/Share/{shareId}")]
    [AllowAnonymous]
    public async Task<IActionResult> ShareAsync([FromRoute] string shareId, [FromQuery] StatsRequest request, CancellationToken cancellationToken)
    {
        var site = await this._siteLogic.GetSiteAsync(HttpUtility.UrlDecode(shareId));
        if (site == null)
        {
            return NotFound();
        }
        
        // no access when subscription expired
        var organization = await _organizationLogic.GetOrganizationAsync(site.OrganizationId);
        if (!_subscriptionPlanGuard.IsSubscriptionPlanExpired(organization))
        {
            return NotFound();
        }

        ViewBag.Request = request;
        ViewBag.LinkBuilder = new StatsRequestLinkBuilder(request);
        var stats = await _statsLogic.GetStatsAsync(site, request, cancellationToken);

        var viewModel = this.StatsToViewModel(stats, site);
        return View(viewModel);
    }

    [HttpGet("Stats/Live/{siteId}")]
    public async Task<IActionResult> LiveAsync([FromRoute] Guid siteId, CancellationToken cancellationToken)
    {
        var userId = HttpContext.User.GetUserId();
        var organizationId = HttpContext.User.GetOrganizationId();
        var site = await this._siteLogic.GetSiteAsync(userId, organizationId, siteId);
        if (site == null)
        {
            return NotFound();
        }

        var organization = await _organizationLogic.GetOrganizationAsync(organizationId);
        if (!_subscriptionPlanGuard.IsSubscriptionPlanExpired(organization))
        {
            return RedirectToAction("Index", "Site");
        }

        var model = new LiveViewModel
        {
            Site = site,
            UpdateUrl = Url.Action("LiveUpdate", new { siteId })
        };

        return View(model);
    }

    [HttpGet("Stats/LiveUpdate/{siteId}")]
    public async Task<IActionResult> LiveUpdateAsync([FromRoute] Guid siteId, CancellationToken cancellationToken)
    {
        var userId = HttpContext.User.GetUserId();
        var organizationId = HttpContext.User.GetOrganizationId();
        
        var to = DateTime.Now;
        var from = DateTime.Now.AddMinutes(-15);
        var data = await _siteLogic.GetRawDataAsync(userId, organizationId, siteId, from, to);

        return View(data.ToList());
    }

    private StatsViewModel StatsToViewModel(StatsData data, Site site)
    {
        var usersChart = new LineChartViewModel
        {
            Series = new List<TimeSeriesViewModel>()
        };

        usersChart.Series.Add(GetTimeSeries(data.UsersOverTime, "Użytkownicy"));
        usersChart.Series.Add(GetTimeSeries(data.EngagedUsersOverTime, "Zaangażowani użytkownicy"));

        var pageViewsChart = new LineChartViewModel
        {
            Series = new List<TimeSeriesViewModel>()
        };

        pageViewsChart.Series.Add(GetTimeSeries(data.PageViewsOverTime, "Odsłony"));

        var timeOnSiteChart = new LineChartViewModel
        {
            Series = new List<TimeSeriesViewModel>()
        };

        timeOnSiteChart.Series.Add(GetTimeSeries(data.AverageTimeOnSiteOverTime, "time"));

        var stats = new StatsViewModel()
        {
            Summary = new StatsSummaryViewModel
            {
                TotalUsersCount = data.Summary.TotalUsersCount,
                TotalUsersChange = null,
                TotalEngagedUsersCount = data.Summary.TotalEngagedUsersCount,
                TotalEngagedUsersChange = null,
                TotalPageViews = data.Summary.TotalPageViews,
                TotalPageViewChange = null,
                TotalCustomEvents = data.Summary.TotalCustomEvents,
                AverageVisitLength = data.Summary.AverageVisitLength,
                AverageVisitLengthChange = null,
            },
            UsersInTime = usersChart,
            PageViewsInTime = pageViewsChart,
            AverageVisitLengthInTime = timeOnSiteChart,
            TrafficSources = this.GetTable(data.TrafficSource, StatsRequestFitlerType.ByReferrer),
            Browsers = this.GetPieChart(data.Browsers),
            OSs = this.GetPieChart(data.OSs),
            TouchScreens = this.GetPieChart(data.TouchScreens),
            ScreenSizes = this.GetPieChart(data.ScreenSizes),
            Campaigns = GetTable(data.Campaigns, StatsRequestFitlerType.ByUtmCampaign),
            EntryPages = GetTable(data.EntryPages, StatsRequestFitlerType.ByUrl),
            Languages = GetTable(data.Languages, StatsRequestFitlerType.ByLang),
            PagesWithMostEngagement = GetTable(data.PagesWithMostEngagement, StatsRequestFitlerType.ByUrl),
            PageViews = GetTable(data.PageViews, StatsRequestFitlerType.ByUrl),
            Countries = GetTable(data.Countries, StatsRequestFitlerType.ByCountry),
            Cities = GetTable(data.Cities, StatsRequestFitlerType.ByCity),
            EventNames = GetTable(data.EventNames, StatsRequestFitlerType.ByEventName),
            Site = site
        };

        return stats;
    }

    private TimeSeriesViewModel GetTimeSeries(IList<KeyValuePair<DateTimeOffset, long>> viewsOverTime, string name)
    {
        return
            new TimeSeriesViewModel
            {
                Name = name,
                Values = viewsOverTime.Select(kv => new TimeSeriesValuePoint { TimePoint = kv.Key, Value = kv.Value }).ToList(),
            };
    }

    private TableViewModel GetTable(IList<KeyValuePair<string, long>> payload, StatsRequestFitlerType filterType)
    {
        var data = new DataTable();
        data.Columns.Add("Nazwa");
        data.Columns.Add("Zdarzenia");

        foreach (var kvp in payload)
        {
            data.Rows.Add(kvp.Key, kvp.Value);
        }

        return new TableViewModel { Data = data, FilterType = filterType };
    }

    private PieChartViewModel GetPieChart(IList<KeyValuePair<string, long>> items)
    {
        var result = new PieChartViewModel
        {
            Items = new List<PieChartItem>()
        };

        var total = items.Sum(x => x.Value);
        foreach (var item in items)
        {
            int share = (int)(total / item.Value);
            result.Items.Add(new PieChartItem { Name = item.Key, Value = item.Value });
        }

        return result;
    }
}

src/StatsBro.Host.Panel/Views/Site/DataExport.cshtml
@model Site
@{
    Layout = "_Layout";
}
<div class="pagetitle">
    <h1>Eksport danych @Model.Domain</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Site" asp-action="Index">Strony</a></li>
            <li class="breadcrumb-item active">Eksport danych @Model.Domain</li>
        </ol>
    </nav>
</div><!-- End Page Title -->

<div class="card col-12 col-md-6">
    <div class="card-body">
        <h5 class="card-title">Eksport danych dla strony @Model.Domain</h5>
        <form class="row g-3" method="get" target="_blank" asp-action="DataExportFile" asp-route-siteid="@Model.Id">
            <div class="col-12">
                <label for="inputDate" class="col-sm-2 col-form-label">Dzień od</label>
                <div class="col-sm-10">
                    <input type="date" class="form-control" name="From" required>
                </div>
            </div>

            <div class="col-12">
                <label for="inputDate" class="col-sm-2 col-form-label">Dzień do</label>
                <div class="col-sm-10">
                    <input type="date" class="form-control" name="To" required>
                </div>
            </div>

            <div class="col-12">
                <input type="hidden" name="id" value="@Model.Id" />
                <button class="btn btn-primary" type="submit">Eksportuj</button>
            </div>

        </form>

        <div class="alert alert-info mt-3" role="alert">
            Eksport zawiera dane źródłowe o zdarzeniach.
            Ta opcja umożliwia eksport pierwszych 10 000 zdarzeń z wybranego okresu.
            Jeśli potrzebujesz wyeksportować większą ilość danych wystarczy, że prześlesz do nas taką prośbę.
        </div>
    </div>
</div>

src/StatsBro.Host.Panel/Views/Site/Index.cshtml
@model List<Site>
@{
    Layout = "_Layout";
}
<div class="pagetitle">
    <h1>Strony</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item active"><a asp-controller="Site" asp-action="Index">Strony</a></li>
        </ol>
    </nav>
</div><!-- End Page Title -->

@if (User.IsInRole(StatsBro.Domain.Models.DTO.OrganizationUserRole.Admin.ToString()) && ViewBag.CanAddMoreDomains)
{
    <div class="row mb-3">
        <div class="col">
            <a asp-controller="Site" asp-action="New" class="btn btn-primary"><i class="bi bi-plus-square"></i> Dodaj stronę</a>
        </div>
    </div>    
}

<div class="row row-cols-1 row-cols-sm-2 row-cols-lg-4 g-2">
    @foreach (var site in Model)
    {
        <div class="col">
            <div class="card mr-2">
                <div class="card-body">
                    <h5 class="card-title pb-0">@site.Domain</h5>
                    @if (site.IsScriptLive)
                    {
                        <span class="badge bg-success">Status OK</span>
                    }
                    else
                    {
                        <span class="badge bg-danger">Dane nie są zbierane</span>
                    }
                    <ul class="list-unstyled mt-3">
                        <li class="lead"><a asp-controller="Stats" asp-action="View" asp-route-siteId="@site.Id"><i class="bi bi-bar-chart-line-fill"></i> Statystyki</a></li>
                        <li><a asp-controller="Stats" asp-action="Live" asp-route-siteId="@site.Id"><i class="bi bi-broadcast"></i> Podgląd na żywo</a></li>
                        
                    @if (User.IsInRole(StatsBro.Domain.Models.DTO.OrganizationUserRole.Admin.ToString()))
                    {
                        <li><a asp-controller="Site" asp-action="Settings" asp-route-siteId="@site.Id"><i class="bi bi-gear"></i> Ustawienia strony</a></li>
                        <li><a asp-controller="Site" asp-action="DataExport" asp-route-siteId="@site.Id"><i class="bi bi-cloud-download"></i> Eksport danych</a></li>
                    }
                        
                        <li><a asp-controller="Site" asp-action="Script" asp-route-siteId="@site.Id"><i class="bi bi-code-square"></i> Instalacja skryptu</a></li>
                    </ul>
                </div>
            </div>
        </div>
    }
</div>

src/StatsBro.Host.Panel/Views/Site/New.cshtml
@model AddSiteFormModel
@{
    Layout = "_Layout";
}

<div class="pagetitle">
    <h1>Dodaj nową stronę</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Site" asp-action="Index">Strony</a></li>
            <li class="breadcrumb-item active">Dodaj nową stronę</li>
        </ol>
    </nav>
</div><!-- End Page Title -->
<div class="card col-12 col-md-6">
    <div class="card-body">
        <h5 class="card-title">Nowa strona</h5>
        <form class="row g-3" method="post" asp-action="New">
            @await Html.PartialAsync("/Views/Shared/ValidationErrors.cshtml")
            
            <div class="col-12">
                <label for="yourDomain" class="form-label">Adres strony</label>
                <p class="small text-secondary">Adres strony do zainstalowania statystyk, np. https://mojastrona.com</p>
                <input type="url" name="siteUrl" class="form-control" id="yourDomain" required>
            </div>

            <div class="col-12">
                <button class="btn btn-primary" type="submit">Zapisz</button>
            </div>

        </form>
    </div>
</div>

src/StatsBro.Host.Panel/Views/Site/Script.cshtml
@model Site
@{
    Layout = "_Layout";
}
<div class="pagetitle">
    <h1>Skrypt dla @Model.Domain</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Site" asp-action="Index">Strony</a></li>
            <li class="breadcrumb-item active">Skrypt dla @Model.Domain</li>
        </ol>
    </nav>
</div><!-- End Page Title -->

<div class="card">
    <div class="card-body">
        <h5 class="card-title">Instalacja skryptu dla strony @Model.Domain</h5>
        @if (Model.IsScriptLive)
        {
            <p>Skrypt działa prawidłowo i zbiera dane. <a asp-controller="Stats" asp-action="View" asp-route-siteId="@Model.Id">Zobacz statystyki</a></p>
        }
        else
        {
            <p>
                Umieść proszę poniższy skrypt pomiędzy tagami &#x3C;head&#x3E; i &#x3C;/head&#x3E; we wszystkich częściach Twojej strony internetowej @Model.Domain
            </p>

            <div class="alert alert-secondary" role="alert">
                <code>
                    &#x3C;script defer src=&#x22;https://data.statsbro.io/js/script.js&#x22;&#x3E;&#x3C;/script&#x3E;
                </code>
            </div>

            <p>
                Po umieszczeniu kodu wejdź na stronę i odwiedź kilka jej podstron. Jeśli wszystko poszło dobrze to ten ekran zniknie automatycznie.
            </p>

            <div class="alert alert-secondary" role="alert">
                <h4 class="alert-heading"><img src="~/assets/img/wp_logo.png" height="50" /> Instalacja na Wordpress</h4>

                <p>Skorzystaj z <a href="~/assets/plugins/statsbro_wp_plugin.zip">darmowego pluginu</a> by zainstalować StatsBro na swojej instancji WP</p>
            </div>

            <div class="alert alert-info" role="alert">
                Uwaga! StatsBro automatycznie ignoruje ruch ze środowisk testowych i deweloperskich. Upewnij się, że ruch będzie pochodził dokładnie z domeny o nazwie: @Model.Domain
                (a nie np. subdomeny)
            </div>

            <script type="text/javascript">setTimeout(function () { location.reload(true); }, 10000);</script>
        }
    </div>
</div>

src/StatsBro.Host.Panel/Views/Site/Settings.cshtml
@model SiteSettingsFormModel
@{
    Layout = "_Layout";
}
<div class="pagetitle">
    <h1>Ustawienia @Model.General.Domain</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Site" asp-action="Index">Strony</a></li>
            <li class="breadcrumb-item active">Ustawienia @Model.General.Domain</li>
        </ol>
    </nav>
</div><!-- End Page Title -->
<div class="card col-12 col-lg-8">
    <div class="card-body">
        <h5 class="card-title">Ustawienia @Model.General.Domain</h5>
        
        <ul class="nav nav-tabs" id="settingsTab" role="tablist">
            <li class="nav-item" role="presentation">
                <button class="nav-link active" id="general-tab" data-bs-toggle="tab" data-bs-target="#general" type="button" role="tab" aria-controls="general" aria-selected="true">Podstawowe</button>
            </li>
            <li class="nav-item" role="presentation">
                <button class="nav-link" id="sharing-tab" data-bs-toggle="tab" data-bs-target="#sharing" type="button" role="tab" aria-controls="sharing" aria-selected="false">Udostępnianie</button>
            </li>
        </ul>
        <div class="tab-content pt-2" id="myTabContent">
                <div class="tab-pane fade show active" id="general" role="tabpanel" aria-labelledby="general-tab">
                    @await Html.PartialAsync("/Views/Shared/Settings/General.cshtml", Model.General)
                </div>
                <div class="tab-pane fade" id="sharing" role="tabpanel" aria-labelledby="sharing-tab">
                    @await Html.PartialAsync("/Views/Shared/Settings/Sharing.cshtml", Model.Sharing)
                </div>
        </div>
        
    </div>
</div>

@section Scripts {
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const hash = window.location.hash;
            if (hash != undefined && hash != null && hash != "") {
                const bsTab = new bootstrap.Tab(hash);
                bsTab.show();
            }
        });
        
    </script>
}